apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - image: bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler-1
        envFrom:
        - configMapRef:
            name: synergychat-crawler-configmap
      - image: bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler-2
        # envFrom:
        # - configMapRef:
        #     name: synergychat-crawler-configmap
        env:
          - name: CRAWLER_PORT
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_PORT_2
                name: synergychat-crawler-configmap
          - name: CRAWLER_KEYWORDS
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_KEYWORDS
                name: synergychat-crawler-configmap
          - name: CRAWLER_DB_PATH
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_DB_PATH
                name: synergychat-crawler-configmap
          - name: CRAWLER_DB_PATH
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_DB_PATH
                name: synergychat-crawler-configmap
      - image: bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler-3
        # envFrom:
        # - configMapRef:
        #     name: synergychat-crawler-configmap
        env:
          - name: CRAWLER_PORT
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_PORT_3
                name: synergychat-crawler-configmap
          - name: CRAWLER_KEYWORDS
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_KEYWORDS
                name: synergychat-crawler-configmap
          - name: CRAWLER_DB_PATH
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_DB_PATH
                name: synergychat-crawler-configmap
          - name: CRAWLER_DB_PATH
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_DB_PATH
                name: synergychat-crawler-configmap
      volumes:
      - name: cache-volume
        emptyDir: {}
