apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-web-configmap
data:
  WEB_PORT: "8080"
  API_URL: http://synchatapi.internal
  CRAWLER_BASE_URL: http://crawler-service.crawler.svc.cluster.local